---
# file: main.yml

# Setup Groups
- name: Create group players
  group: name=players state=present
  become: yes
  become_method: sudo


# Setup Users
- name: Create user janitor
  user: name=janitor password={{janitor_password}} groups=players system=yes
  become: yes
  become_method: sudo

# TODO Do we need this?
- name: Setup user janitor
  user: name=janitor generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
  become: yes
  become_method: sudo

- name: Create user gamer
  user: name=gamer password={{gamer_password}} group=players
  become: yes
  become_method: sudo

#- name: TODO Configure wallpaper for users


#- name: TODO Configure autoboot

#- name: TODO Configure splash screen

